name: Renovate Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      checks: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v44.2.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: info