name: EndSectors
main: pl.endixon.sectors.paper.PaperSector
version: 1.7.4
api-version: '1.20'
depend: [ ProtocolLib]
commands:
  sector:
    description: Glowna komenda sektorow
    aliases: [sectors, sektor, sektory]
    permission: endsectors.command.sector
    usage: /<command>
  channel:
    aliases:
      - ch
